id: PBDE1889B
initial_creation_type: input
source_metadata:
  title: Dorje Drolö Series
  language: en
  description: 'Texts related to Dorje Drolö (rdo rje gro lod), a wrathful manifestation
    of Guru Padmasambhava, who is depicted standing upon a pregnant tigress and is
    associated with the elimination of obstacles:'
  volume:
    9dc66d4e51d84cd5aec1abb44d917448:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Sādhanas
    68f8caee472d4b71a1516377990dc5bf:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Sādhanas
    d17ba071c80843a994c25610cf7f2618:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sādhanas
    041b6edd763647568e0f53e402493c4e:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
created_at: '2022-03-01T03:28:31.654123'
last_modified_at: '2022-03-01T03:28:31.654130'
